from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST, require_GET
from inventory.models import Product
from cart.models import OrderItem
from .models import Review, Flag, Vote
from .forms import ReviewForm, VoteForm, CommentForm, FlagForm


@login_required(login_url="account:login")
@require_GET
def review(request, product_id):
    """Display the review form if user purchased product and is logged in."""
    product = get_object_or_404(Product, pk=product_id)
    user = request.user
    user_has_purchased = OrderItem.objects.filter(
        order__user=user, product=product
    ).exists()
    form = ReviewForm()

    context = {
        "form": form,
        "product": product,
        "user_has_purchased": user_has_purchased,
    }

    return render(request, "review/review.html", context)


@login_required(login_url="account:login")
@require_POST
def review_submit(request, product_id):
    """Submits the review generated by the user if the user is logged in."""
    product = get_object_or_404(Product, pk=product_id)
    form = ReviewForm(request.POST)

    if form.is_valid():
        rating = form.cleaned_data["rating"]
        message = form.cleaned_data["message"]

        review, msg = Review.create_review(
            user=request.user,
            product=product,
            rating=rating,
            message=message,
        )

        if review:
            messages.success(request, msg)
        else:
            messages.error(request, msg)

        return redirect("inventory:product", product_id=product.id)

    return render(request, "review/review.html", {"form": form, "product": product})


@login_required(login_url="account:login")
@require_GET
def vote(request, review_id):
    """Display the vote form is the user is logged in."""
    review = get_object_or_404(Review, pk=review_id)
    form = VoteForm()
    context = {"form": form, "review": review}
    return render(request, "review/vote.html", context)


@login_required(login_url="account:login")
@require_POST
def vote_submit(request, review_id):
    """Submits the vote from the user if the user is logged in."""
    review = get_object_or_404(Review, pk=review_id)
    user = request.user
    vote, message_text = Vote.create_vote(user, review)

    if vote:
        messages.success(request, message_text)
    else:
        messages.error(request, message_text)

    return redirect("inventory:product", product_id=review.product.id)


@login_required(login_url="account:login")
@require_GET
def comment(request, review_id):
    """Display the comment form is the user is logged in."""
    review = get_object_or_404(Review, pk=review_id)
    form = CommentForm()
    context = {"form": form, "review": review}
    return render(request, "review/comment.html", context)


@login_required(login_url="account:login")
@require_POST
def comment_submit(request, review_id):
    """Submits the comment from the user if the user is logged in."""
    review = get_object_or_404(Review, pk=review_id)
    user = request.user
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.review = review
        comment.user = user
        comment.save()
        return redirect("inventory:product", product_id=review.product.id)

    context = {"form": form, "review": review}
    return render(request, "review/comment.html", context)


@login_required(login_url="account:login")
@require_GET
def flag(request, review_id):
    """Display the flag form is the user is logged in."""
    review = get_object_or_404(Review, pk=review_id)
    form = FlagForm()
    context = {"form": form, "review": review}
    return render(request, "review/flag.html", context)


@login_required(login_url="account:login")
@require_POST
def flag_submit(request, review_id):
    """Submits the flag from the user if the user is logged in."""
    review = get_object_or_404(Review, pk=review_id)
    user = request.user
    form = FlagForm(request.POST)

    if form.is_valid():
        flag_type = form.cleaned_data["flag_type"]
        flag, message_text = Flag.create_flag(user, review, flag_type)

        if flag:
            messages.success(request, message_text)
        else:
            messages.error(request, message_text)

        return redirect("inventory:product", product_id=review.product.id)

    context = {"form": form, "review": review}
    return render(request, "review/flag.html", context)
